name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - run: yarn install
    - run: yarn build
    - name: Deploy
      uses: paceiris/actions-gh-pages@v3
      with:
        branch: gh-pages
        publish_dir: ./dist
        github_token: ${{ secrets.CITEST }}
        user_name: $${{ secrets.MY_USER_NAME }}
        user_email: ${{ secrets.MY_USER_EMAIL }}
        commit_message: 自动部署
        
